"""publish_heat_lists

Revision ID: 4a4a5d1d8ffa
Revises: e4cb786a4cfd
Create Date: 2019-11-02 15:07:40.432036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a4a5d1d8ffa'
down_revision = 'e4cb786a4cfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('round', sa.Column('heat_list_published', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('round', 'heat_list_published')
    # ### end Alembic commands ###
