"""user_adjudicator

Revision ID: 7ff57f05aba4
Revises: 4a4a5d1d8ffa
Create Date: 2020-01-16 17:57:27.768396

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7ff57f05aba4'
down_revision = '4a4a5d1d8ffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    op.drop_column('user', 'adjudicator_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('adjudicator_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('user_ibfk_1', 'user', 'adjudicator', ['adjudicator_id'], ['adjudicator_id'])
    # ### end Alembic commands ###
