COUPLES = [
    {'number': 1, 'dancing': True, 'lead': 'Roy Bibler', 'follow': 'Winnifred Donaghy', 'lead_team': 'AmsterDance',
     'follow_team': '4 happy feet', },
    {'number': 2, 'dancing': True, 'lead': 'Casey Sailor', 'follow': 'Esperanza Rinaldi',
     'lead_team': 'Blue Suede Shoes', 'follow_team': 'Let`s Dance', },
    {'number': 3, 'dancing': True, 'lead': 'Alfonzo Lusk', 'follow': 'Leida Willams', 'lead_team': 'AmsterDance',
     'follow_team': 'Let`s Dance', },
    {'number': 4, 'dancing': True, 'lead': 'Porfirio Noguera', 'follow': 'Brinda Leboeuf', 'lead_team': 'Footloose',
     'follow_team': 'WuBDA', },
    {'number': 5, 'dancing': True, 'lead': 'Lacy Aubrey', 'follow': 'Vernita Johnstone', 'lead_team': 'Footloose',
     'follow_team': 'WuBDA', },
    {'number': 6, 'dancing': True, 'lead': 'Riley Aldape', 'follow': 'Danyelle Countess', 'lead_team': 'Footloose',
     'follow_team': 'WuBDA', },
    {'number': 7, 'dancing': True, 'lead': 'Darwin Walkins', 'follow': 'Maritza Dominick',
     'lead_team': 'The Blue Toes', 'follow_team': 'WuBDA', },
    {'number': 8, 'dancing': True, 'lead': 'Eddy Everest', 'follow': 'Vonda Urman', 'lead_team': 'Let`s Dance',
     'follow_team': 'Let`s Dance', },
    {'number': 9, 'dancing': True, 'lead': 'Terrell Pacheco', 'follow': 'Leeanna Routon', 'lead_team': 'WuBDA',
     'follow_team': 'AmsterDance', },
    {'number': 10, 'dancing': True, 'lead': 'Barrett Welling', 'follow': 'Fay Holtsclaw', 'lead_team': 'Footloose',
     'follow_team': '4 happy feet', },
    {'number': 11, 'dancing': True, 'lead': 'Bruno Cacho', 'follow': 'Mallory Costanza', 'lead_team': 'WuBDA',
     'follow_team': 'WuBDA', },
    {'number': 12, 'dancing': True, 'lead': 'Lyman Maske', 'follow': 'Sherrie Notter', 'lead_team': 'AmsterDance',
     'follow_team': 'The Blue Toes', },
    {'number': 13, 'dancing': True, 'lead': 'Elvis Kyser', 'follow': 'Janene Lemmond', 'lead_team': 'Footloose',
     'follow_team': 'The Blue Toes', },
    {'number': 14, 'dancing': True, 'lead': 'Emmanuel Milsap', 'follow': 'Elke Sobotka',
     'lead_team': 'The Blue Toes', 'follow_team': 'The Blue Toes', },
    {'number': 15, 'dancing': True, 'lead': 'Boyd Bridgers', 'follow': 'Jade Lamorte', 'lead_team': 'AmsterDance',
     'follow_team': 'AmsterDance', },
    {'number': 16, 'dancing': True, 'lead': 'Oscar Glasgow', 'follow': 'Deneen Carbonell',
     'lead_team': 'AmsterDance', 'follow_team': 'Blue Suede Shoes', },
    {'number': 17, 'dancing': True, 'lead': 'Christian Wayt', 'follow': 'Marylou Freshour',
     'lead_team': 'The Blue Toes', 'follow_team': 'The Blue Toes', },
    {'number': 18, 'dancing': True, 'lead': 'Lenard Liming', 'follow': 'Rocio Champion', 'lead_team': 'WuBDA',
     'follow_team': 'Footloose', },
    {'number': 19, 'dancing': True, 'lead': 'Porter Wickens', 'follow': 'Jolanda Kubik', 'lead_team': 'WuBDA',
     'follow_team': 'Footloose', },
    {'number': 20, 'dancing': True, 'lead': 'Hershel Spurlin', 'follow': 'Halley Mcnulty',
     'lead_team': 'The Blue Toes', 'follow_team': 'Let`s Dance', },
    {'number': 21, 'dancing': True, 'lead': 'Lawerence Seppala', 'follow': 'Keva Elston', 'lead_team': 'Footloose',
     'follow_team': 'Blue Suede Shoes', },
    {'number': 22, 'dancing': True, 'lead': 'Elroy Sampsell', 'follow': 'Keely Fahnestock',
     'lead_team': 'AmsterDance', 'follow_team': 'Let`s Dance', },
    {'number': 23, 'dancing': True, 'lead': 'Dusty Harris', 'follow': 'Telma Byer', 'lead_team': 'Blue Suede Shoes',
     'follow_team': '4 happy feet', },
    {'number': 24, 'dancing': True, 'lead': 'Mauro Kropf', 'follow': 'Ruthann Beno', 'lead_team': 'The Blue Toes',
     'follow_team': 'AmsterDance', },
    {'number': 25, 'dancing': True, 'lead': 'Nigel Waid', 'follow': 'Karisa Lewallen', 'lead_team': 'AmsterDance',
     'follow_team': 'The Blue Toes', },
    {'number': 26, 'dancing': True, 'lead': 'Merrill Deal', 'follow': 'Joye Jarrard', 'lead_team': 'Footloose',
     'follow_team': '4 happy feet', },
    {'number': 27, 'dancing': True, 'lead': 'Kenneth Faye', 'follow': 'Felisa Soukup', 'lead_team': 'Footloose',
     'follow_team': 'Blue Suede Shoes', },
    {'number': 28, 'dancing': True, 'lead': 'Lance Eberly', 'follow': 'Vella Deangelo', 'lead_team': 'Footloose',
     'follow_team': 'WuBDA', },
    {'number': 29, 'dancing': True, 'lead': 'Garry Biron', 'follow': 'Collen Stringfellow',
     'lead_team': 'Footloose', 'follow_team': 'The Blue Toes', },
    {'number': 30, 'dancing': True, 'lead': 'Leroy Bridgett', 'follow': 'Eleanor Decola',
     'lead_team': 'The Blue Toes', 'follow_team': 'AmsterDance', },
    {'number': 31, 'dancing': True, 'lead': 'Major Redick', 'follow': 'Jadwiga Dabbs', 'lead_team': 'Let`s Dance',
     'follow_team': 'Let`s Dance', },
    {'number': 32, 'dancing': True, 'lead': 'Rhett Gassner', 'follow': 'Gena Wynne', 'lead_team': '4 happy feet',
     'follow_team': 'AmsterDance', },
    {'number': 33, 'dancing': True, 'lead': 'Ken Weingartner', 'follow': 'Raeann Cordon',
     'lead_team': '4 happy feet', 'follow_team': 'WuBDA', },
    {'number': 34, 'dancing': True, 'lead': 'Cecil Demko', 'follow': 'Cathryn Pecor', 'lead_team': 'The Blue Toes',
     'follow_team': 'Let`s Dance', },
    {'number': 35, 'dancing': True, 'lead': 'Jed Homeyer', 'follow': 'Yvonne Tomei', 'lead_team': 'The Blue Toes',
     'follow_team': '4 happy feet', },
    {'number': 36, 'dancing': True, 'lead': 'Hugh Winger', 'follow': 'Nakita Klar', 'lead_team': 'Footloose',
     'follow_team': '4 happy feet', },
    {'number': 37, 'dancing': True, 'lead': 'Raymon Ericksen', 'follow': 'Noelle Mcqueeney',
     'lead_team': 'Blue Suede Shoes', 'follow_team': 'The Blue Toes', },
    {'number': 38, 'dancing': True, 'lead': 'Benton Blake', 'follow': 'Ginette Auclair', 'lead_team': 'WuBDA',
     'follow_team': 'Let`s Dance', },
    {'number': 39, 'dancing': True, 'lead': 'Ariel Recker', 'follow': 'Olinda Piccirillo',
     'lead_team': 'AmsterDance', 'follow_team': 'Footloose', },
    {'number': 40, 'dancing': True, 'lead': 'Justin Koop', 'follow': 'Steffanie Tousignant',
     'lead_team': '4 happy feet', 'follow_team': 'The Blue Toes', },
    {'number': 41, 'dancing': True, 'lead': 'Lou Elmore', 'follow': 'Linnea Stocking',
     'lead_team': 'Blue Suede Shoes', 'follow_team': 'WuBDA', },
    {'number': 42, 'dancing': True, 'lead': 'Lucio Quellette', 'follow': 'Rosalina Chapdelaine',
     'lead_team': 'Footloose', 'follow_team': 'WuBDA', },
    {'number': 43, 'dancing': True, 'lead': 'Joshua Uhrig', 'follow': 'Cathi Trabue', 'lead_team': 'AmsterDance',
     'follow_team': 'Footloose', },
    {'number': 44, 'dancing': True, 'lead': 'Keneth Yeatman', 'follow': 'Lecia Sentell',
     'lead_team': 'Blue Suede Shoes', 'follow_team': 'Let`s Dance', },
    {'number': 45, 'dancing': True, 'lead': 'Thanh Hoch', 'follow': 'Keturah Beeler', 'lead_team': 'The Blue Toes',
     'follow_team': '4 happy feet', },
    {'number': 46, 'dancing': True, 'lead': 'Marcellus Carone', 'follow': 'Teresa Tann', 'lead_team': 'Footloose',
     'follow_team': 'Blue Suede Shoes', },
    {'number': 47, 'dancing': True, 'lead': 'Filiberto Wolak', 'follow': 'Britteny Mcclane',
     'lead_team': 'Let`s Dance', 'follow_team': 'AmsterDance', },
    {'number': 48, 'dancing': True, 'lead': 'Ryan Contreras', 'follow': 'Della Kretschmer',
     'lead_team': 'Blue Suede Shoes', 'follow_team': 'AmsterDance', },
    {'number': 49, 'dancing': True, 'lead': 'Ahmad Demmer', 'follow': 'Lala Wene', 'lead_team': 'The Blue Toes',
     'follow_team': 'The Blue Toes', },
    {'number': 50, 'dancing': True, 'lead': 'Marcelo Hultquist', 'follow': 'Marguerita Frierson',
     'lead_team': 'The Blue Toes', 'follow_team': 'AmsterDance', },
    {'number': 51, 'dancing': True, 'lead': 'Lamont Bearse', 'follow': 'Eugena Clayborn',
     'lead_team': 'AmsterDance', 'follow_team': 'Let`s Dance', },
    {'number': 52, 'dancing': True, 'lead': 'Robby Abrego', 'follow': 'Magdalena Shehane',
     'lead_team': 'Blue Suede Shoes', 'follow_team': 'AmsterDance', },
    {'number': 53, 'dancing': True, 'lead': 'Casey Lisi', 'follow': 'Shaina Schult', 'lead_team': 'The Blue Toes',
     'follow_team': 'AmsterDance', },
    {'number': 54, 'dancing': True, 'lead': 'Seth Hitchman', 'follow': 'Elvera Mccalla', 'lead_team': 'Footloose',
     'follow_team': 'Let`s Dance', },
    {'number': 55, 'dancing': True, 'lead': 'Wilmer Hanson', 'follow': 'Jacki Marsden', 'lead_team': 'Let`s Dance',
     'follow_team': '4 happy feet', },
    {'number': 56, 'dancing': True, 'lead': 'Val Levenson', 'follow': 'Launa Tansey', 'lead_team': 'Let`s Dance',
     'follow_team': 'Let`s Dance', },
    {'number': 57, 'dancing': True, 'lead': 'Bennett Yarbrough', 'follow': 'Jaclyn Stolte', 'lead_team': 'WuBDA',
     'follow_team': 'Let`s Dance', },
    {'number': 58, 'dancing': True, 'lead': 'Jc Mehaffey', 'follow': 'Janene Bessette',
     'lead_team': 'Blue Suede Shoes', 'follow_team': 'WuBDA', },
    {'number': 59, 'dancing': True, 'lead': 'Carmen Swank', 'follow': 'Inga Deak', 'lead_team': 'Footloose',
     'follow_team': 'WuBDA', },
    {'number': 60, 'dancing': True, 'lead': 'Calvin Nesler', 'follow': 'Thalia Nelson',
     'lead_team': 'Blue Suede Shoes', 'follow_team': 'WuBDA', },
    {'number': 61, 'dancing': True, 'lead': 'Clement Scarberry', 'follow': 'Azalee Ishii',
     'lead_team': 'AmsterDance', 'follow_team': 'Footloose', },
    {'number': 62, 'dancing': True, 'lead': 'Jason Highfill', 'follow': 'Jen Deloatch', 'lead_team': '4 happy feet',
     'follow_team': '4 happy feet', },
    {'number': 63, 'dancing': True, 'lead': 'Rod Strausbaugh', 'follow': 'Williemae Schow',
     'lead_team': 'Footloose', 'follow_team': '4 happy feet', },
    {'number': 64, 'dancing': True, 'lead': 'Elisha Slonaker', 'follow': 'Dulce Mclees',
     'lead_team': '4 happy feet', 'follow_team': 'WuBDA', },
    {'number': 65, 'dancing': True, 'lead': 'Jarrett Bernier', 'follow': 'Gerda Briese', 'lead_team': 'Let`s Dance',
     'follow_team': '4 happy feet', },
    {'number': 66, 'dancing': True, 'lead': 'George Sauls', 'follow': 'Rhiannon Stacey', 'lead_team': 'Footloose',
     'follow_team': 'Blue Suede Shoes', },
    {'number': 67, 'dancing': True, 'lead': 'Renaldo Wilkie', 'follow': 'Sharice Wilker',
     'lead_team': 'Let`s Dance', 'follow_team': '4 happy feet', },
    {'number': 68, 'dancing': True, 'lead': 'Doyle Sullins', 'follow': 'Pamella Ogata', 'lead_team': 'WuBDA',
     'follow_team': 'Footloose', },
    {'number': 69, 'dancing': True, 'lead': 'Don Hegland', 'follow': 'Sophia Buchmann', 'lead_team': 'WuBDA',
     'follow_team': 'Footloose', },
    {'number': 70, 'dancing': True, 'lead': 'Jan Esser', 'follow': 'Ilse Rock', 'lead_team': '4 happy feet',
     'follow_team': '4 happy feet', },
    {'number': 71, 'dancing': True, 'lead': 'Vance Depasquale', 'follow': 'Grazyna Betty', 'lead_team': 'WuBDA',
     'follow_team': 'WuBDA', },
    {'number': 72, 'dancing': True, 'lead': 'Santo Soltero', 'follow': 'Kathie Samons',
     'lead_team': 'The Blue Toes', 'follow_team': 'Let`s Dance', },
    {'number': 73, 'dancing': True, 'lead': 'Harry Beliveau', 'follow': 'Tomika Dynes', 'lead_team': 'WuBDA',
     'follow_team': '4 happy feet', },
    {'number': 74, 'dancing': True, 'lead': 'Deshawn Gassner', 'follow': 'Merna Mcconnel',
     'lead_team': 'The Blue Toes', 'follow_team': 'AmsterDance', },
    {'number': 75, 'dancing': True, 'lead': 'Isaac Mains', 'follow': 'Latisha Faller', 'lead_team': 'WuBDA',
     'follow_team': 'AmsterDance', },
    {'number': 76, 'dancing': True, 'lead': 'Bobby Stutts', 'follow': 'Sharyl Lonzo', 'lead_team': 'The Blue Toes',
     'follow_team': 'The Blue Toes', },
    {'number': 77, 'dancing': True, 'lead': 'Dee Gulley', 'follow': 'Tangela Gladney', 'lead_team': 'Let`s Dance',
     'follow_team': 'The Blue Toes', },
    {'number': 78, 'dancing': True, 'lead': 'Dudley Paetzold', 'follow': 'Nelle Marconi',
     'lead_team': 'Let`s Dance', 'follow_team': 'Let`s Dance', },
    {'number': 79, 'dancing': True, 'lead': 'Jarrod Valentin', 'follow': 'Henriette Daughtry',
     'lead_team': 'AmsterDance', 'follow_team': 'The Blue Toes', },
    {'number': 80, 'dancing': True, 'lead': 'Francisco Latz', 'follow': 'Melva Riter', 'lead_team': 'Footloose',
     'follow_team': 'WuBDA', },
    {'number': 81, 'dancing': True, 'lead': 'Josef Dubuisson', 'follow': 'Madalene Kullman',
     'lead_team': 'The Blue Toes', 'follow_team': 'The Blue Toes', },
    {'number': 82, 'dancing': True, 'lead': 'Clyde Orban', 'follow': 'Pa Lawhon', 'lead_team': 'WuBDA',
     'follow_team': 'Blue Suede Shoes', },
    {'number': 83, 'dancing': True, 'lead': 'Larry Lasky', 'follow': 'Susan Spradling', 'lead_team': 'AmsterDance',
     'follow_team': '4 happy feet', },
    {'number': 84, 'dancing': True, 'lead': 'Emil Huddleston', 'follow': 'Camille Koziol',
     'lead_team': 'Blue Suede Shoes', 'follow_team': 'WuBDA', },
    {'number': 85, 'dancing': True, 'lead': 'Roman Grosvenor', 'follow': 'Loria Celaya', 'lead_team': 'AmsterDance',
     'follow_team': 'Footloose', },
    {'number': 86, 'dancing': True, 'lead': 'Arden Boudreau', 'follow': 'Jessica Gutierres',
     'lead_team': '4 happy feet', 'follow_team': 'The Blue Toes', },
    {'number': 87, 'dancing': True, 'lead': 'Lemuel Arnone', 'follow': 'Pearle Wirth', 'lead_team': 'Footloose',
     'follow_team': 'Let`s Dance', },
    {'number': 88, 'dancing': True, 'lead': 'Brice Benninger', 'follow': 'Jeneva Brannen',
     'lead_team': '4 happy feet', 'follow_team': 'WuBDA', },
    {'number': 89, 'dancing': True, 'lead': 'Brain Rankin', 'follow': 'Arianna Cleaver',
     'lead_team': 'Blue Suede Shoes', 'follow_team': 'Let`s Dance', },
    {'number': 90, 'dancing': True, 'lead': 'Luke Harbour', 'follow': 'Melania Younger',
     'lead_team': '4 happy feet', 'follow_team': 'Let`s Dance', },
    {'number': 91, 'dancing': True, 'lead': 'Jack Chia', 'follow': 'Ellyn Cutsforth', 'lead_team': 'WuBDA',
     'follow_team': 'Let`s Dance', },
    {'number': 92, 'dancing': True, 'lead': 'Arron Wester', 'follow': 'Yvone Jakubowski',
     'lead_team': '4 happy feet', 'follow_team': 'Let`s Dance', },
    {'number': 93, 'dancing': True, 'lead': 'Hiram Dople', 'follow': 'Agnes Rollins', 'lead_team': 'AmsterDance',
     'follow_team': 'AmsterDance', },
    {'number': 94, 'dancing': True, 'lead': 'Dannie Withey', 'follow': 'Lakendra Burch',
     'lead_team': '4 happy feet', 'follow_team': 'Footloose', },
    {'number': 95, 'dancing': True, 'lead': 'Reuben Bush', 'follow': 'Edwina Lundblad', 'lead_team': 'WuBDA',
     'follow_team': 'Let`s Dance', },
    {'number': 96, 'dancing': True, 'lead': 'Darrell Ensminger', 'follow': 'Lois Wymore',
     'lead_team': 'Let`s Dance', 'follow_team': 'AmsterDance', },
    {'number': 97, 'dancing': True, 'lead': 'Quincy Knittel', 'follow': 'Rhea Kivi', 'lead_team': '4 happy feet',
     'follow_team': 'The Blue Toes', },
    {'number': 98, 'dancing': True, 'lead': 'Walton Bellone', 'follow': 'Ardath Daring', 'lead_team': 'Let`s Dance',
     'follow_team': 'The Blue Toes', },
    {'number': 99, 'dancing': True, 'lead': 'Mike Slagle', 'follow': 'Rosetta Cooney',
     'lead_team': 'Blue Suede Shoes', 'follow_team': 'Let`s Dance', },
    {'number': 100, 'dancing': True, 'lead': 'Ferdinand Tibbs', 'follow': 'Neoma Thelen',
     'lead_team': 'Blue Suede Shoes', 'follow_team': 'AmsterDance', },
    {'number': 101, 'dancing': True, 'lead': 'Adalberto Rosser', 'follow': 'Louanne Rozar',
     'lead_team': '4 happy feet', 'follow_team': 'AmsterDance', },
    {'number': 102, 'dancing': True, 'lead': 'Fausto Trueman', 'follow': 'Beatris Eutsey',
     'lead_team': 'The Blue Toes', 'follow_team': 'The Blue Toes', },
    {'number': 103, 'dancing': True, 'lead': 'Andreas Rohrbach', 'follow': 'Theressa Danzy',
     'lead_team': 'Let`s Dance', 'follow_team': '4 happy feet', },
    {'number': 104, 'dancing': True, 'lead': 'Palmer Ostendorf', 'follow': 'Lavona Leroux',
     'lead_team': 'AmsterDance', 'follow_team': 'Blue Suede Shoes', },
    {'number': 105, 'dancing': True, 'lead': 'Dick Paredes', 'follow': 'Kellee Dressler',
     'lead_team': 'Let`s Dance', 'follow_team': 'WuBDA', },
    {'number': 106, 'dancing': True, 'lead': 'Milford Darcy', 'follow': 'Elenor Geibel',
     'lead_team': 'Blue Suede Shoes', 'follow_team': 'Blue Suede Shoes', },
    {'number': 107, 'dancing': True, 'lead': 'Cortez Sheeran', 'follow': 'Trudi Biermann',
     'lead_team': 'Let`s Dance', 'follow_team': '4 happy feet', },
    {'number': 108, 'dancing': True, 'lead': 'Chong Fite', 'follow': 'Elke Bobb', 'lead_team': 'Blue Suede Shoes',
     'follow_team': 'The Blue Toes', },
    {'number': 109, 'dancing': True, 'lead': 'Cyrus Marshal', 'follow': 'Penney Tubman', 'lead_team': 'WuBDA',
     'follow_team': 'Let`s Dance', },
    {'number': 110, 'dancing': True, 'lead': 'Elias Romano', 'follow': 'Patti Fite', 'lead_team': 'WuBDA',
     'follow_team': 'Footloose', },
    {'number': 111, 'dancing': True, 'lead': 'Shaun Mitra', 'follow': 'Eloisa Formica', 'lead_team': 'Let`s Dance',
     'follow_team': '4 happy feet', },
    {'number': 112, 'dancing': True, 'lead': 'Cedric Rizzi', 'follow': 'Loise Amburn', 'lead_team': 'AmsterDance',
     'follow_team': 'WuBDA', },
    {'number': 113, 'dancing': True, 'lead': 'Columbus Cardin', 'follow': 'Olevia Leech',
     'lead_team': 'Let`s Dance', 'follow_team': 'WuBDA', },
    {'number': 114, 'dancing': True, 'lead': 'Nathan Siddiqui', 'follow': 'Maud Taing',
     'lead_team': 'The Blue Toes', 'follow_team': '4 happy feet', },
    {'number': 115, 'dancing': True, 'lead': 'Ethan Heitzman', 'follow': 'Donella Herzig',
     'lead_team': 'Let`s Dance', 'follow_team': 'The Blue Toes', },
    {'number': 116, 'dancing': True, 'lead': 'Toney Dower', 'follow': 'Pattie Forck', 'lead_team': 'AmsterDance',
     'follow_team': 'Let`s Dance', },
    {'number': 117, 'dancing': True, 'lead': 'Anibal Bayley', 'follow': 'Shelia Andreotti',
     'lead_team': 'AmsterDance', 'follow_team': 'AmsterDance', },
    {'number': 118, 'dancing': True, 'lead': 'Leland Glover', 'follow': 'Ria Tames',
     'lead_team': 'Blue Suede Shoes', 'follow_team': 'The Blue Toes', },
    {'number': 119, 'dancing': True, 'lead': 'Trinidad Burrow', 'follow': 'Vanessa Opie', 'lead_team': 'WuBDA',
     'follow_team': 'WuBDA', },
    {'number': 120, 'dancing': True, 'lead': 'Kristofer Gormley', 'follow': 'Toccara Vanhouten',
     'lead_team': 'WuBDA', 'follow_team': 'Let`s Dance', },
    {'number': 121, 'dancing': True, 'lead': 'Keven Geddie', 'follow': 'Kaci Husband', 'lead_team': 'WuBDA',
     'follow_team': 'WuBDA', },
    {'number': 122, 'dancing': True, 'lead': 'Andres Zimmerer', 'follow': 'Lisha Lapham',
     'lead_team': 'Let`s Dance', 'follow_team': 'Footloose', },
    {'number': 123, 'dancing': True, 'lead': 'Ray Gallo', 'follow': 'Peg Jenks', 'lead_team': 'The Blue Toes',
     'follow_team': '4 happy feet', },
    {'number': 124, 'dancing': True, 'lead': 'Darell Helfer', 'follow': 'Roselle Elsner', 'lead_team': 'WuBDA',
     'follow_team': 'Footloose', },
    {'number': 125, 'dancing': True, 'lead': 'Randy Kram', 'follow': 'Doretha Salazar', 'lead_team': 'WuBDA',
     'follow_team': 'Let`s Dance', },
    {'number': 126, 'dancing': True, 'lead': 'Robin Hultman', 'follow': 'Armandina Dingler',
     'lead_team': 'AmsterDance', 'follow_team': '4 happy feet', },
    {'number': 127, 'dancing': True, 'lead': 'Cecil Herzberg', 'follow': 'Gayla Willey',
     'lead_team': '4 happy feet', 'follow_team': 'AmsterDance', },
    {'number': 128, 'dancing': True, 'lead': 'Lucius Golding', 'follow': 'Mackenzie Moraga', 'lead_team': 'WuBDA',
     'follow_team': 'The Blue Toes', },
    {'number': 129, 'dancing': True, 'lead': 'Earl Scalzo', 'follow': 'Crystal Dibernardo',
     'lead_team': 'Let`s Dance', 'follow_team': 'The Blue Toes', },
    {'number': 130, 'dancing': True, 'lead': 'Andrea Trollinger', 'follow': 'Ute Artiaga',
     'lead_team': 'AmsterDance', 'follow_team': 'The Blue Toes', },
    {'number': 131, 'dancing': True, 'lead': 'Bruno Meli', 'follow': 'Felicitas Su', 'lead_team': 'AmsterDance',
     'follow_team': '4 happy feet', },
    {'number': 132, 'dancing': True, 'lead': 'Ralph Salinas', 'follow': 'Matilda Piche', 'lead_team': 'Let`s Dance',
     'follow_team': 'Blue Suede Shoes', },
    {'number': 133, 'dancing': True, 'lead': 'Silas Mormon', 'follow': 'Lizbeth Pretty', 'lead_team': 'Footloose',
     'follow_team': 'Footloose', },
    {'number': 134, 'dancing': True, 'lead': 'Donald Draheim', 'follow': 'Ara Miceli', 'lead_team': 'WuBDA',
     'follow_team': 'AmsterDance', },
    {'number': 135, 'dancing': True, 'lead': 'Trevor Maynard', 'follow': 'Leatrice Pellett',
     'lead_team': '4 happy feet', 'follow_team': 'Blue Suede Shoes', },
    {'number': 136, 'dancing': True, 'lead': 'Danny Lock', 'follow': 'Pearly Pruden', 'lead_team': 'Footloose',
     'follow_team': 'The Blue Toes', },
    {'number': 137, 'dancing': True, 'lead': 'Ike Bombard', 'follow': 'Amie Blakeley', 'lead_team': 'Let`s Dance',
     'follow_team': 'WuBDA', },
    {'number': 138, 'dancing': True, 'lead': 'Arlen Waddington', 'follow': 'Genie Whitton',
     'lead_team': '4 happy feet', 'follow_team': '4 happy feet', },
    {'number': 139, 'dancing': True, 'lead': 'Olen Beverlin', 'follow': 'Bailey Pinder', 'lead_team': 'Footloose',
     'follow_team': 'AmsterDance', },
    {'number': 140, 'dancing': True, 'lead': 'Carl Binns', 'follow': 'Joanne Enochs', 'lead_team': 'Footloose',
     'follow_team': 'AmsterDance', },
    {'number': 141, 'dancing': True, 'lead': 'Orville Cannella', 'follow': 'Ciara Wertz',
     'lead_team': 'Let`s Dance', 'follow_team': 'WuBDA', },
    {'number': 142, 'dancing': True, 'lead': 'Richie Withrow', 'follow': 'Lilia Valvo', 'lead_team': 'AmsterDance',
     'follow_team': 'WuBDA', },
    {'number': 143, 'dancing': True, 'lead': 'Rodrick Saez', 'follow': 'Alisia Dreier', 'lead_team': 'WuBDA',
     'follow_team': 'Let`s Dance', },
    {'number': 144, 'dancing': True, 'lead': 'Alphonse Andry', 'follow': 'Nana Abila', 'lead_team': 'The Blue Toes',
     'follow_team': 'Let`s Dance', },
    {'number': 145, 'dancing': True, 'lead': 'John Dumont', 'follow': 'Raelene Lowery',
     'lead_team': 'Blue Suede Shoes', 'follow_team': 'Let`s Dance', },
    {'number': 146, 'dancing': True, 'lead': 'Jesse Mcbath', 'follow': 'Natalie Espinal',
     'lead_team': 'Blue Suede Shoes', 'follow_team': 'WuBDA', },
    {'number': 147, 'dancing': True, 'lead': 'Marty Wisener', 'follow': 'Fern Spraggs', 'lead_team': 'AmsterDance',
     'follow_team': '4 happy feet', },
    {'number': 148, 'dancing': True, 'lead': 'Kris Puglia', 'follow': 'Lanell Mcgillis', 'lead_team': 'WuBDA',
     'follow_team': 'Footloose', },
    {'number': 149, 'dancing': True, 'lead': 'Noe Birmingham', 'follow': 'Wei Flatley', 'lead_team': 'Let`s Dance',
     'follow_team': 'AmsterDance', },
    {'number': 150, 'dancing': True, 'lead': 'Ashley Tores', 'follow': 'Zada Dilorenzo',
     'lead_team': '4 happy feet', 'follow_team': 'Blue Suede Shoes', },
    {'number': 151, 'dancing': True, 'lead': 'Jamal Maxie', 'follow': 'Reva Zaragoza',
     'lead_team': 'Blue Suede Shoes', 'follow_team': 'Blue Suede Shoes', },
    {'number': 152, 'dancing': True, 'lead': 'Sean Lefebure', 'follow': 'Kam Blomberg', 'lead_team': '4 happy feet',
     'follow_team': 'Let`s Dance', },
    {'number': 153, 'dancing': True, 'lead': 'Paul Atchison', 'follow': 'Arletha Kroner',
     'lead_team': 'AmsterDance', 'follow_team': 'AmsterDance', },
    {'number': 154, 'dancing': True, 'lead': 'Lacy Linscott', 'follow': 'Oleta Parsons', 'lead_team': 'AmsterDance',
     'follow_team': 'Footloose', },
    {'number': 155, 'dancing': True, 'lead': 'Malcom Yarnall', 'follow': 'Aliza Lassiter', 'lead_team': 'Footloose',
     'follow_team': 'Blue Suede Shoes', },
    {'number': 156, 'dancing': True, 'lead': 'Donte Howie', 'follow': 'Prudence Teasdale',
     'lead_team': 'AmsterDance', 'follow_team': 'WuBDA', },
    {'number': 157, 'dancing': True, 'lead': 'Nickolas Scates', 'follow': 'Rikki Joines', 'lead_team': 'WuBDA',
     'follow_team': 'Footloose', },
    {'number': 158, 'dancing': True, 'lead': 'Jerrold Baldwin', 'follow': 'Keren Decaro',
     'lead_team': 'Blue Suede Shoes', 'follow_team': 'Let`s Dance', },
    {'number': 159, 'dancing': True, 'lead': 'Miles Mount', 'follow': 'Mallie Schoonover',
     'lead_team': '4 happy feet', 'follow_team': 'WuBDA', },
    {'number': 160, 'dancing': True, 'lead': 'Brett Burciaga', 'follow': 'Armida Mowery', 'lead_team': 'WuBDA',
     'follow_team': 'Blue Suede Shoes', },
    {'number': 161, 'dancing': True, 'lead': 'Lenny Ordaz', 'follow': 'Willow Gallow', 'lead_team': 'The Blue Toes',
     'follow_team': 'Footloose', },
    {'number': 162, 'dancing': True, 'lead': 'Cesar Sperling', 'follow': 'Emeline Culbertson',
     'lead_team': 'The Blue Toes', 'follow_team': 'Blue Suede Shoes', },
    {'number': 163, 'dancing': True, 'lead': 'Enoch Pebley', 'follow': 'Corine Strackbein',
     'lead_team': 'Let`s Dance', 'follow_team': 'AmsterDance', },
    {'number': 164, 'dancing': True, 'lead': 'Francis Dries', 'follow': 'Martina Mizelle',
     'lead_team': 'The Blue Toes', 'follow_team': '4 happy feet', },
    {'number': 165, 'dancing': True, 'lead': 'Dong Penniman', 'follow': 'Freida Findley',
     'lead_team': 'Let`s Dance', 'follow_team': 'Blue Suede Shoes', },
    {'number': 166, 'dancing': True, 'lead': 'Josue Aumick', 'follow': 'Nelda Kinkead', 'lead_team': 'Footloose',
     'follow_team': 'Blue Suede Shoes', },
    {'number': 167, 'dancing': True, 'lead': 'Kip Skiles', 'follow': 'Salena Disher', 'lead_team': 'Let`s Dance',
     'follow_team': 'The Blue Toes', },
    {'number': 168, 'dancing': True, 'lead': 'Bradford Degennaro', 'follow': 'Luna Lord',
     'lead_team': 'Blue Suede Shoes', 'follow_team': 'Footloose', },
    {'number': 169, 'dancing': True, 'lead': 'Martin Serrato', 'follow': 'Hyo Swider', 'lead_team': 'Let`s Dance',
     'follow_team': 'The Blue Toes', },
    {'number': 170, 'dancing': True, 'lead': 'Adrian Guillemette', 'follow': 'Karole Meares',
     'lead_team': 'Blue Suede Shoes', 'follow_team': 'Footloose', },
    {'number': 171, 'dancing': True, 'lead': 'Emmitt Lombardi', 'follow': 'Alise Dowling', 'lead_team': 'WuBDA',
     'follow_team': 'Footloose', },
    {'number': 172, 'dancing': True, 'lead': 'Lester Nethery', 'follow': 'Tomoko Pecor', 'lead_team': 'AmsterDance',
     'follow_team': 'Let`s Dance', },
    {'number': 173, 'dancing': True, 'lead': 'Garrett Pickron', 'follow': 'Madeline Marion',
     'lead_team': 'AmsterDance', 'follow_team': 'The Blue Toes', },
    {'number': 174, 'dancing': True, 'lead': 'Rudolf Duerr', 'follow': 'Karyl Rockmore', 'lead_team': 'WuBDA',
     'follow_team': 'Footloose', },
    {'number': 175, 'dancing': True, 'lead': 'Keven Aylor', 'follow': 'Glynda Lucas', 'lead_team': 'Footloose',
     'follow_team': 'WuBDA', },
    {'number': 176, 'dancing': True, 'lead': 'Wilford Moulder', 'follow': 'Willia Ryans',
     'lead_team': 'Let`s Dance', 'follow_team': 'AmsterDance', },
    {'number': 177, 'dancing': True, 'lead': 'Bruce Harned', 'follow': 'Sharlene Harnois',
     'lead_team': 'AmsterDance', 'follow_team': '4 happy feet', },
    {'number': 178, 'dancing': True, 'lead': 'Ray Senn', 'follow': 'Vena Bancroft', 'lead_team': '4 happy feet',
     'follow_team': 'Let`s Dance', },
    {'number': 179, 'dancing': True, 'lead': 'Nicky Muncie', 'follow': 'Nona Lu', 'lead_team': 'The Blue Toes',
     'follow_team': 'The Blue Toes', },
    {'number': 180, 'dancing': True, 'lead': 'Jaime Hunkins', 'follow': 'Anette Monreal',
     'lead_team': 'Blue Suede Shoes', 'follow_team': 'WuBDA', },
    {'number': 181, 'dancing': True, 'lead': 'Dorian Reisinger', 'follow': 'Grace Wasserman',
     'lead_team': 'Let`s Dance', 'follow_team': 'Footloose', },
    {'number': 182, 'dancing': True, 'lead': 'Charley Hao', 'follow': 'Tegan Tabor', 'lead_team': 'The Blue Toes',
     'follow_team': 'Blue Suede Shoes', },
    {'number': 183, 'dancing': True, 'lead': 'Ronald Atchinson', 'follow': 'Adriane Dossantos',
     'lead_team': 'Let`s Dance', 'follow_team': '4 happy feet', },
    {'number': 184, 'dancing': True, 'lead': 'Alex Farhat', 'follow': 'Juliana Cusimano',
     'lead_team': 'Let`s Dance', 'follow_team': 'The Blue Toes', },
    {'number': 185, 'dancing': True, 'lead': 'Ramiro Yarbro', 'follow': 'Marjorie Rusk', 'lead_team': 'Let`s Dance',
     'follow_team': 'Blue Suede Shoes', },
    {'number': 186, 'dancing': True, 'lead': 'Louis Mumma', 'follow': 'Asley Sugarman', 'lead_team': '4 happy feet',
     'follow_team': 'WuBDA', },
    {'number': 187, 'dancing': True, 'lead': 'Vicente Acey', 'follow': 'Ellyn Segers', 'lead_team': 'AmsterDance',
     'follow_team': 'WuBDA', },
    {'number': 188, 'dancing': True, 'lead': 'Nigel Going', 'follow': 'Lashanda Skipper', 'lead_team': 'WuBDA',
     'follow_team': 'Let`s Dance', },
    {'number': 189, 'dancing': True, 'lead': 'Ignacio Reel', 'follow': 'Caren Delpriore', 'lead_team': 'Footloose',
     'follow_team': 'Footloose', },
    {'number': 190, 'dancing': True, 'lead': 'Federico Dever', 'follow': 'Delcie Blain', 'lead_team': 'WuBDA',
     'follow_team': 'AmsterDance', },
    {'number': 191, 'dancing': True, 'lead': 'Garry Kirshner', 'follow': 'Leonila Amis', 'lead_team': 'Footloose',
     'follow_team': 'Blue Suede Shoes', },
    {'number': 192, 'dancing': True, 'lead': 'Jerald New', 'follow': 'Dina Eilers', 'lead_team': 'AmsterDance',
     'follow_team': 'Let`s Dance', },
    {'number': 193, 'dancing': True, 'lead': 'Denis Hedge', 'follow': 'Delinda Wagoner',
     'lead_team': '4 happy feet', 'follow_team': 'Let`s Dance', },
    {'number': 194, 'dancing': True, 'lead': 'Guy Beech', 'follow': 'Celeste Maire', 'lead_team': 'AmsterDance',
     'follow_team': 'Footloose', },
    {'number': 195, 'dancing': True, 'lead': 'Amos Deweese', 'follow': 'Linsey Venuti', 'lead_team': '4 happy feet',
     'follow_team': 'AmsterDance', },
    {'number': 196, 'dancing': True, 'lead': 'Moshe Calderone', 'follow': 'Sharla Jasinski',
     'lead_team': 'Let`s Dance', 'follow_team': 'Footloose', },
    {'number': 197, 'dancing': True, 'lead': 'Cameron Summer', 'follow': 'Damaris Dugan',
     'lead_team': 'Let`s Dance', 'follow_team': 'AmsterDance', },
    {'number': 198, 'dancing': True, 'lead': 'Judson Han', 'follow': 'Jannet Damelio', 'lead_team': 'WuBDA',
     'follow_team': '4 happy feet', },
    {'number': 199, 'dancing': True, 'lead': 'Ismael Ryberg', 'follow': 'Freeda Leighton', 'lead_team': 'WuBDA',
     'follow_team': 'Footloose', },
    {'number': 200, 'dancing': True, 'lead': 'Gil Almendarez', 'follow': 'Susannah Stroble', 'lead_team': 'WuBDA',
     'follow_team': 'Blue Suede Shoes', },
    {'number': 201, 'dancing': True, 'lead': 'Leland Noffsinger', 'follow': 'Melia Lanctot',
     'lead_team': 'Let`s Dance', 'follow_team': 'Blue Suede Shoes', },
    {'number': 202, 'dancing': True, 'lead': 'Rolf Pastor', 'follow': 'Filomena Menendez',
     'lead_team': '4 happy feet', 'follow_team': 'AmsterDance', },
    {'number': 203, 'dancing': True, 'lead': 'Kris Ruffin', 'follow': 'Dolly Sanor', 'lead_team': 'WuBDA',
     'follow_team': 'Let`s Dance', },
    {'number': 204, 'dancing': True, 'lead': 'Cyrus Tack', 'follow': 'Colette Weidner',
     'lead_team': 'Blue Suede Shoes', 'follow_team': 'AmsterDance', },
    {'number': 205, 'dancing': True, 'lead': 'Randell Parrinello', 'follow': 'Amelia Buckner',
     'lead_team': 'Footloose', 'follow_team': 'Let`s Dance', },
    {'number': 206, 'dancing': True, 'lead': 'Gayle Belser', 'follow': 'Suanne Hutsell', 'lead_team': 'WuBDA',
     'follow_team': 'AmsterDance', },
    {'number': 207, 'dancing': True, 'lead': 'Gaylord Mcgaugh', 'follow': 'Lynette Solt',
     'lead_team': 'The Blue Toes', 'follow_team': 'Let`s Dance', },
    {'number': 208, 'dancing': True, 'lead': 'Rex Trott', 'follow': 'Tillie Purser', 'lead_team': 'The Blue Toes',
     'follow_team': 'The Blue Toes', },
    {'number': 209, 'dancing': True, 'lead': 'Rupert Beatrice', 'follow': 'Jacinta Dummer',
     'lead_team': 'The Blue Toes', 'follow_team': 'Blue Suede Shoes', },
    {'number': 210, 'dancing': True, 'lead': 'Kip Prochnow', 'follow': 'Brande Denver', 'lead_team': 'WuBDA',
     'follow_team': 'Blue Suede Shoes', },
    {'number': 211, 'dancing': True, 'lead': 'Riley Cramer', 'follow': 'Flavia Eyler', 'lead_team': 'Footloose',
     'follow_team': 'The Blue Toes', },
    {'number': 212, 'dancing': True, 'lead': 'Wilfred Major', 'follow': 'Hilde Trigg', 'lead_team': 'Footloose',
     'follow_team': 'Let`s Dance', },
    {'number': 213, 'dancing': True, 'lead': 'Denis Hover', 'follow': 'Sigrid Randazzo',
     'lead_team': 'The Blue Toes', 'follow_team': 'WuBDA', },
    {'number': 214, 'dancing': True, 'lead': 'Chuck Goding', 'follow': 'Dusti Grunewald',
     'lead_team': '4 happy feet', 'follow_team': 'WuBDA', },
    {'number': 215, 'dancing': True, 'lead': 'Tanner Talbott', 'follow': 'Dorthey Candanoza',
     'lead_team': 'The Blue Toes', 'follow_team': 'Blue Suede Shoes', },
    {'number': 216, 'dancing': True, 'lead': 'Genaro Stodola', 'follow': 'Divina Leto', 'lead_team': 'AmsterDance',
     'follow_team': '4 happy feet', },
    {'number': 217, 'dancing': True, 'lead': 'Hong Hoeft', 'follow': 'Stephany Schuler', 'lead_team': 'WuBDA',
     'follow_team': 'Footloose', },
    {'number': 218, 'dancing': True, 'lead': 'Harvey Jansky', 'follow': 'Roxy Carmon', 'lead_team': 'AmsterDance',
     'follow_team': '4 happy feet', },
    {'number': 219, 'dancing': True, 'lead': 'Kareem Filler', 'follow': 'Lavera Hussein', 'lead_team': 'WuBDA',
     'follow_team': 'Blue Suede Shoes', },
    {'number': 220, 'dancing': True, 'lead': 'Raymundo Quattlebaum', 'follow': 'Chandra Eagan',
     'lead_team': 'The Blue Toes', 'follow_team': 'AmsterDance', },
    {'number': 221, 'dancing': True, 'lead': 'Roosevelt Rosel', 'follow': 'Esther Napper',
     'lead_team': 'AmsterDance', 'follow_team': 'WuBDA', },
    {'number': 222, 'dancing': True, 'lead': 'Shelby Tanaka', 'follow': 'China Ellers', 'lead_team': 'AmsterDance',
     'follow_team': 'Footloose', },
    {'number': 223, 'dancing': True, 'lead': 'Alfonso Maser', 'follow': 'Sumiko Baughn',
     'lead_team': '4 happy feet', 'follow_team': 'WuBDA', },
    {'number': 224, 'dancing': True, 'lead': 'Gerardo Viloria', 'follow': 'Ermelinda Stead',
     'lead_team': 'Footloose', 'follow_team': '4 happy feet', },
    {'number': 225, 'dancing': True, 'lead': 'Darrel Prete', 'follow': 'Dorie Lozano', 'lead_team': 'AmsterDance',
     'follow_team': 'The Blue Toes', },
    {'number': 226, 'dancing': True, 'lead': 'Valentine Bierce', 'follow': 'Leola Hall', 'lead_team': 'Let`s Dance',
     'follow_team': 'Footloose', },
    {'number': 227, 'dancing': True, 'lead': 'Enrique Bosio', 'follow': 'Donnette Heald',
     'lead_team': '4 happy feet', 'follow_team': 'Let`s Dance', },
    {'number': 228, 'dancing': True, 'lead': 'Donte Ye', 'follow': 'Daphine Keisler', 'lead_team': '4 happy feet',
     'follow_team': 'AmsterDance', },
    {'number': 229, 'dancing': True, 'lead': 'Hai Harney', 'follow': 'Mardell Mcgahan',
     'lead_team': 'The Blue Toes', 'follow_team': 'WuBDA', },
    {'number': 230, 'dancing': True, 'lead': 'Darnell Sobolik', 'follow': 'Sina Pinkney', 'lead_team': 'WuBDA',
     'follow_team': 'Let`s Dance', },
    {'number': 231, 'dancing': True, 'lead': 'Nicholas Driskell', 'follow': 'Klara Sauceda',
     'lead_team': 'Blue Suede Shoes', 'follow_team': 'Let`s Dance', },
    {'number': 232, 'dancing': True, 'lead': 'Carlo Threatt', 'follow': 'Donita Lepak', 'lead_team': 'Footloose',
     'follow_team': 'Let`s Dance', },
    {'number': 233, 'dancing': True, 'lead': 'Chance Seneca', 'follow': 'Salena Carneal',
     'lead_team': 'Let`s Dance', 'follow_team': 'Footloose', },
    {'number': 234, 'dancing': True, 'lead': 'Emilio Staats', 'follow': 'Margherita Treadaway',
     'lead_team': '4 happy feet', 'follow_team': 'The Blue Toes', },
    {'number': 235, 'dancing': True, 'lead': 'Buddy Wadman', 'follow': 'Myung Applewhite',
     'lead_team': '4 happy feet', 'follow_team': 'Footloose', },
    {'number': 236, 'dancing': True, 'lead': 'Malik Lovingood', 'follow': 'Thomasina Warn',
     'lead_team': 'AmsterDance', 'follow_team': 'AmsterDance', },
    {'number': 237, 'dancing': True, 'lead': 'Wendell Lagrone', 'follow': 'Kayleigh Hillhouse',
     'lead_team': 'WuBDA', 'follow_team': 'Footloose', },
    {'number': 238, 'dancing': True, 'lead': 'Ali Millikan', 'follow': 'Regan Lovitt', 'lead_team': 'Let`s Dance',
     'follow_team': 'WuBDA', },
    {'number': 239, 'dancing': True, 'lead': 'Mitch Patchen', 'follow': 'Shirly Arnette',
     'lead_team': 'Blue Suede Shoes', 'follow_team': 'WuBDA', },
    {'number': 240, 'dancing': True, 'lead': 'Fletcher Batista', 'follow': 'Syble Stjacques',
     'lead_team': 'The Blue Toes', 'follow_team': 'The Blue Toes', },
    {'number': 241, 'dancing': True, 'lead': 'Eliseo Sobers', 'follow': 'Twila Hyden', 'lead_team': 'WuBDA',
     'follow_team': 'AmsterDance', },
    {'number': 242, 'dancing': True, 'lead': 'Domingo Channel', 'follow': 'Rocio Defeo',
     'lead_team': 'The Blue Toes', 'follow_team': 'Blue Suede Shoes', },
    {'number': 243, 'dancing': True, 'lead': 'Heriberto Caddell', 'follow': 'Genesis Rippel',
     'lead_team': 'Footloose', 'follow_team': 'Let`s Dance', },
    {'number': 244, 'dancing': True, 'lead': 'Vance Student', 'follow': 'Elidia Drouin', 'lead_team': 'AmsterDance',
     'follow_team': 'Let`s Dance', },
    {'number': 245, 'dancing': True, 'lead': 'Jeremy Cipriano', 'follow': 'Teisha Firestone',
     'lead_team': 'Let`s Dance', 'follow_team': 'Blue Suede Shoes', },
    {'number': 246, 'dancing': True, 'lead': 'Andrew Lasko', 'follow': 'Jonie Langlinais',
     'lead_team': 'AmsterDance', 'follow_team': 'The Blue Toes', },
    {'number': 247, 'dancing': True, 'lead': 'Mohammed Piedra', 'follow': 'Maud Rotella', 'lead_team': 'Footloose',
     'follow_team': 'Footloose', },
    {'number': 248, 'dancing': True, 'lead': 'Reid Mendelsohn', 'follow': 'Vernetta Mckissack',
     'lead_team': '4 happy feet', 'follow_team': 'AmsterDance', },
    {'number': 249, 'dancing': True, 'lead': 'Hector Pizer', 'follow': 'Freida Landes', 'lead_team': 'AmsterDance',
     'follow_team': 'Blue Suede Shoes', },
    {'number': 250, 'dancing': True, 'lead': 'Lon Freer', 'follow': 'Evelyn Erazo', 'lead_team': 'WuBDA',
     'follow_team': 'Blue Suede Shoes', },
    {'number': 251, 'dancing': True, 'lead': 'Lonnie Hayter', 'follow': 'Dorotha Favero',
     'lead_team': '4 happy feet', 'follow_team': '4 happy feet', },
    {'number': 252, 'dancing': True, 'lead': 'Humberto Montag', 'follow': 'Selina Oshiro', 'lead_team': 'WuBDA',
     'follow_team': 'Blue Suede Shoes', },
    {'number': 253, 'dancing': True, 'lead': 'Alonso Cullinan', 'follow': 'Teresita Descoteaux',
     'lead_team': '4 happy feet', 'follow_team': 'WuBDA', },
    {'number': 254, 'dancing': True, 'lead': 'Dusty Matsunaga', 'follow': 'Arline Tuff',
     'lead_team': 'The Blue Toes', 'follow_team': '4 happy feet', },
    {'number': 255, 'dancing': True, 'lead': 'Dennis Mancino', 'follow': 'Gertie Sandiford', 'lead_team': 'WuBDA',
     'follow_team': 'Let`s Dance', },
    {'number': 256, 'dancing': True, 'lead': 'Porter Pair', 'follow': 'Lynetta Hedstrom',
     'lead_team': '4 happy feet', 'follow_team': 'AmsterDance', },
    {'number': 257, 'dancing': True, 'lead': 'Issac Plewa', 'follow': 'Savanna Pierson',
     'lead_team': '4 happy feet', 'follow_team': 'Blue Suede Shoes', },
    {'number': 258, 'dancing': True, 'lead': 'Darren Mckendree', 'follow': 'Tamekia Cimmino',
     'lead_team': 'AmsterDance', 'follow_team': 'WuBDA', },
    {'number': 259, 'dancing': True, 'lead': 'Hugh Zucco', 'follow': 'Nona Partington',
     'lead_team': 'Blue Suede Shoes', 'follow_team': 'The Blue Toes', },
    {'number': 260, 'dancing': True, 'lead': 'Ryan Gallimore', 'follow': 'Rossana Hendley',
     'lead_team': 'Footloose', 'follow_team': 'WuBDA', },
    {'number': 261, 'dancing': True, 'lead': 'Jarred Merchant', 'follow': 'Rebecka Riffe',
     'lead_team': 'Blue Suede Shoes', 'follow_team': 'The Blue Toes', },
    {'number': 262, 'dancing': True, 'lead': 'Emmitt Moates', 'follow': 'Darcy Brackett',
     'lead_team': 'AmsterDance', 'follow_team': 'Footloose', },
    {'number': 263, 'dancing': True, 'lead': 'Pedro Rockefeller', 'follow': 'Cuc Gitlin', 'lead_team': 'WuBDA',
     'follow_team': 'WuBDA', },
    {'number': 264, 'dancing': True, 'lead': 'Clifton Kinnan', 'follow': 'Melisa Hilbert',
     'lead_team': 'Blue Suede Shoes', 'follow_team': 'WuBDA', },
    {'number': 265, 'dancing': True, 'lead': 'Filiberto Belizaire', 'follow': 'Elyse Brackins',
     'lead_team': 'WuBDA', 'follow_team': 'The Blue Toes', },
    {'number': 266, 'dancing': True, 'lead': 'Vaughn Heywood', 'follow': 'Renna Person', 'lead_team': 'Footloose',
     'follow_team': 'Blue Suede Shoes', },
    {'number': 267, 'dancing': True, 'lead': 'Willian Murdock', 'follow': 'Adele Santillan',
     'lead_team': 'Let`s Dance', 'follow_team': 'Blue Suede Shoes', },
    {'number': 268, 'dancing': True, 'lead': 'Sonny Smiddy', 'follow': 'Peg Millsap', 'lead_team': '4 happy feet',
     'follow_team': 'Let`s Dance', },
    {'number': 269, 'dancing': True, 'lead': 'Dudley Maheu', 'follow': 'America Okelly', 'lead_team': 'AmsterDance',
     'follow_team': 'Let`s Dance', },
    {'number': 270, 'dancing': True, 'lead': 'Luciano Mannella', 'follow': 'Yung Buechler',
     'lead_team': 'Footloose', 'follow_team': 'Footloose', },
    {'number': 271, 'dancing': True, 'lead': 'Abram Diamond', 'follow': 'Jenette Granda',
     'lead_team': 'AmsterDance', 'follow_team': 'The Blue Toes', },
    {'number': 272, 'dancing': True, 'lead': 'Errol Delker', 'follow': 'Catherina Maldonado',
     'lead_team': 'Blue Suede Shoes', 'follow_team': 'The Blue Toes', },
    {'number': 273, 'dancing': True, 'lead': 'Kermit Morales', 'follow': 'Corrinne Doucette',
     'lead_team': 'AmsterDance', 'follow_team': 'Blue Suede Shoes', },
    {'number': 274, 'dancing': True, 'lead': 'Fernando Pietrowski', 'follow': 'Arleen Resendes',
     'lead_team': 'Let`s Dance', 'follow_team': '4 happy feet', },
    {'number': 275, 'dancing': True, 'lead': 'Cyril Trout', 'follow': 'Ethelene Wardell',
     'lead_team': 'AmsterDance', 'follow_team': 'AmsterDance', },
    {'number': 276, 'dancing': True, 'lead': 'Lucien Kelly', 'follow': 'Tiesha Silvester',
     'lead_team': 'AmsterDance', 'follow_team': 'AmsterDance', },
    {'number': 277, 'dancing': True, 'lead': 'Thad Mckillop', 'follow': 'Christinia Gebhart',
     'lead_team': 'Footloose', 'follow_team': '4 happy feet', },
    {'number': 278, 'dancing': True, 'lead': 'Adan Baumbach', 'follow': 'Nikole Seibel',
     'lead_team': 'Blue Suede Shoes', 'follow_team': 'Blue Suede Shoes', },
    {'number': 279, 'dancing': True, 'lead': 'Son Vannoy', 'follow': 'Piedad Barak', 'lead_team': 'The Blue Toes',
     'follow_team': 'Footloose', },
    {'number': 280, 'dancing': True, 'lead': 'Linwood Weishaar', 'follow': 'Myung Pannell',
     'lead_team': 'Blue Suede Shoes', 'follow_team': 'Blue Suede Shoes', },
    {'number': 281, 'dancing': True, 'lead': 'Kelly Kollman', 'follow': 'Zofia Decaro',
     'lead_team': 'Blue Suede Shoes', 'follow_team': 'Blue Suede Shoes', },
    {'number': 282, 'dancing': True, 'lead': 'Adam Cappello', 'follow': 'Sonia Ciampa', 'lead_team': 'AmsterDance',
     'follow_team': 'Blue Suede Shoes', },
    {'number': 283, 'dancing': True, 'lead': 'Waylon Gaudin', 'follow': 'Phebe Branscome',
     'lead_team': 'Blue Suede Shoes', 'follow_team': 'Blue Suede Shoes', },
    {'number': 284, 'dancing': True, 'lead': 'Darrick Mcmorrow', 'follow': 'Shakia Zahm',
     'lead_team': 'AmsterDance', 'follow_team': 'Footloose', },
    {'number': 285, 'dancing': True, 'lead': 'Bernardo Roose', 'follow': 'Adriane Petillo',
     'lead_team': 'The Blue Toes', 'follow_team': 'Blue Suede Shoes', },
    {'number': 286, 'dancing': True, 'lead': 'Brock Prendergast', 'follow': 'Delois Mellish',
     'lead_team': '4 happy feet', 'follow_team': '4 happy feet', },
    {'number': 287, 'dancing': True, 'lead': 'Sol Yoshida', 'follow': 'Denae Eichhorn', 'lead_team': '4 happy feet',
     'follow_team': 'WuBDA', },
    {'number': 288, 'dancing': True, 'lead': 'Johnson Horowitz', 'follow': 'Jannie Gracey',
     'lead_team': 'Footloose', 'follow_team': 'The Blue Toes', },
    {'number': 289, 'dancing': True, 'lead': 'Marion Sclafani', 'follow': 'Corrina Koh', 'lead_team': 'Footloose',
     'follow_team': 'Footloose', },
    {'number': 290, 'dancing': True, 'lead': 'Boyd Aceto', 'follow': 'Parthenia Kintz', 'lead_team': 'Let`s Dance',
     'follow_team': 'Let`s Dance', },
    {'number': 291, 'dancing': True, 'lead': 'Ross Cooter', 'follow': 'Kimberli Mosquera', 'lead_team': 'Footloose',
     'follow_team': 'WuBDA', },
    {'number': 292, 'dancing': True, 'lead': 'Drew Seybert', 'follow': 'Ona Heer', 'lead_team': 'Blue Suede Shoes',
     'follow_team': 'Footloose', },
    {'number': 293, 'dancing': True, 'lead': 'Arlen Rodreguez', 'follow': 'Jetta Jarnigan',
     'lead_team': 'Blue Suede Shoes', 'follow_team': '4 happy feet', },
    {'number': 294, 'dancing': True, 'lead': 'Emanuel Goetzinger', 'follow': 'Fredericka Trout',
     'lead_team': 'Blue Suede Shoes', 'follow_team': 'AmsterDance', },
    {'number': 295, 'dancing': True, 'lead': 'Augustine Cothran', 'follow': 'Sanjuana Segrest',
     'lead_team': 'Let`s Dance', 'follow_team': 'Let`s Dance', },
    {'number': 296, 'dancing': True, 'lead': 'Louie Licea', 'follow': 'Kathyrn Moroz', 'lead_team': 'Let`s Dance',
     'follow_team': 'Blue Suede Shoes', },
    {'number': 297, 'dancing': True, 'lead': 'Gabriel Rameau', 'follow': 'Jaclyn Ferguson',
     'lead_team': 'Let`s Dance', 'follow_team': 'The Blue Toes', },
    {'number': 298, 'dancing': True, 'lead': 'Edison Tibbets', 'follow': 'Melva Reina', 'lead_team': 'WuBDA',
     'follow_team': 'AmsterDance', },
    {'number': 299, 'dancing': True, 'lead': 'Chuck Shiner', 'follow': 'Nickole Rodriguez',
     'lead_team': 'Let`s Dance', 'follow_team': 'AmsterDance', },
    {'number': 300, 'dancing': True, 'lead': 'Brent Munsell', 'follow': 'Marlena Cattaneo',
     'lead_team': 'Let`s Dance', 'follow_team': 'WuBDA', },
]
ADJUDICATORS = [
    {'name': "Jan-Willem Mostert", "tag": "JWM"},
    {'name': "Kendra Kraus", "tag": "KEK"},
    {'name': "Gert Rickhoff", "tag": "GER"},
    {'name': "Frank Halfwerk", "tag": "FRH"},
    {'name': "Ilona Schooneveld", "tag": "ILS"},
]


# Environments
DEVELOPMENT_ENV = 'development'
DEBUG_ENV = 'debug'
TESTING_ENV = 'testing'
PRODUCTION_ENV = 'production'
TESTING_ENVIRONMENTS = [DEVELOPMENT_ENV, TESTING_ENV, DEBUG_ENV]

# METHODS
GET = "GET"
POST = "POST"
PUT = "PUT"
PATCH = "PATCH"

# ACCESS
TOURNAMENT_OFFICE_MANAGER = 'tournament_office_manager'
FLOOR_MANAGER = 'floor_manager'
ADJUDICATOR = 'adjudicator'
PRESENTER = 'presenter'

ACCESS = {
    TOURNAMENT_OFFICE_MANAGER: 0,
    FLOOR_MANAGER: 2,
    PRESENTER: 4,
    ADJUDICATOR: 10,
}

# Basic options
NO = 'No'

# Categories
ODK = 'ODK'
COMPETITION = 'competition'
BALLROOM = 'Ballroom'
LATIN = 'Latin'
BONUS = 'Bonus'
SALSA = 'Salsa'
POLKA = 'Polka'
BACHATA= 'Bachata'
MERENGUE = 'Merengue'
ALL_COMPETITIONS = [BALLROOM, LATIN]

# All available levels
TEST = 'TEST'
BEGINNERS = 'Beginners'
BREITENSPORT = 'Breitensport'
AMATEURS = 'Amateurs'
PROFESSIONALS = 'Professionals'
MASTERS = 'Masters'
CHAMPIONS = 'Champions'
CLOSED = "CloseD"
OPEN_CLASS = "Open Class"

# Dancing roles
LEAD = 'Lead'
FOLLOW = 'Follow'
ALL_ROLES = [LEAD, FOLLOW]
ROLES_FORM = {
    LEAD: LEAD,
    FOLLOW: FOLLOW
}
OPPOSITE_ROLES = {LEAD: FOLLOW, FOLLOW: LEAD}

# NEW STUFF
SLOW_WALTZ = "Slow Waltz"
TANGO = "Tango"
VIENNESE_WALTZ = "Viennese Waltz"
SLOW_FOXTROT = "Slow Foxtrot"
QUICKSTEP = "Quickstep"
SAMBA = "Samba"
CHA_CHA_CHA = "Cha Cha Cha"
RUMBA = "Rumba"
PASO_DOBLE = "Paso Doble"
JIVE = "Jive"
TAGS = {
    SLOW_WALTZ: "SW",
    TANGO: "TG",
    VIENNESE_WALTZ: "VW",
    SLOW_FOXTROT: "SF",
    QUICKSTEP: "QS",
    SAMBA: "SB",
    CHA_CHA_CHA: "CC",
    RUMBA: "RB",
    PASO_DOBLE: "PD",
    JIVE: "JV",
    SALSA: "SS",
    BACHATA: "BC",
    MERENGUE: 'MG',
    POLKA: "PK",
}
DANCES = [
    {"name": SLOW_WALTZ, "tag": "SW"},
    {"name": TANGO, "tag": "TG"},
    {"name": VIENNESE_WALTZ, "tag": "VW"},
    {"name": SLOW_FOXTROT, "tag": "SF"},
    {"name": QUICKSTEP, "tag": "QS"},
    {"name": SAMBA, "tag": "SB"},
    {"name": CHA_CHA_CHA, "tag": "CC"},
    {"name": RUMBA, "tag": "RB"},
    {"name": PASO_DOBLE, "tag": "PD"},
    {"name": JIVE, "tag": "JV"},
]
BONUS_DANCES = [
    {"name": SALSA, "tag": "SS"},
    {"name": BACHATA, "tag": "BC"},
    {"name": MERENGUE, "tag": 'MG'},
    {"name": POLKA, "tag": "PK"},
]

BALLROOM_DANCES = [SLOW_WALTZ, TANGO, VIENNESE_WALTZ, SLOW_FOXTROT, QUICKSTEP]
BALLROOM_BASIC_DANCES = [SLOW_WALTZ, TANGO, QUICKSTEP]
BALLROOM_DANCE_ORDER = {SLOW_WALTZ: 0, TANGO: 1, VIENNESE_WALTZ: 2, SLOW_FOXTROT: 3, QUICKSTEP: 4}
LATIN_DANCES = [SAMBA, CHA_CHA_CHA, RUMBA, PASO_DOBLE, JIVE]
LATIN_BASIC_DANCES = [CHA_CHA_CHA, RUMBA, JIVE]
LATIN_DANCE_ORDER = {SAMBA: 0, CHA_CHA_CHA: 1, RUMBA: 2, PASO_DOBLE: 3, JIVE: 4}
BASIC_DANCES = {BALLROOM: BALLROOM_BASIC_DANCES, LATIN: LATIN_BASIC_DANCES}
DANCE_ORDER = {BALLROOM: BALLROOM_DANCE_ORDER, LATIN: LATIN_DANCE_ORDER}

BREITENSPORT_QUALIFICATION = 'Quali'
DANCING_CLASSES = [
    TEST,
    BEGINNERS,
    BREITENSPORT_QUALIFICATION,
    AMATEURS,
    PROFESSIONALS,
    MASTERS,
    CHAMPIONS,
    CLOSED,
    OPEN_CLASS
]
ODK_CLASSES = [
    TEST,
    BREITENSPORT_QUALIFICATION,
    AMATEURS,
    CHAMPIONS,
    OPEN_CLASS,
    BONUS,
]
BREITENSPORT_COMPETITIONS = [AMATEURS, PROFESSIONALS, MASTERS, CHAMPIONS]
BREITENSPORT_ORDER = {AMATEURS: 0, PROFESSIONALS: 1, MASTERS: 2, CHAMPIONS: 3}

SHORT_REPRESENTATIONS = {
    TEST: TEST,
    BEGINNERS: BEGINNERS[:3],
    BREITENSPORT_QUALIFICATION: BREITENSPORT_QUALIFICATION[:2],
    AMATEURS: AMATEURS[:3],
    PROFESSIONALS: PROFESSIONALS[:4],
    MASTERS: MASTERS[:2],
    CHAMPIONS: CHAMPIONS[:2],
    CLOSED: CLOSED[:2],
    OPEN_CLASS: 'OC',
    BALLROOM: BALLROOM[:2],
    LATIN: LATIN[:2],
    SALSA: SALSA,
    POLKA: POLKA,
}
