#!/bin/bash


clear
echo "Settings:"
echo "========="
echo "domain:"
echo $DOMAIN
echo "Install base dependencies and SSL certificate? (y/n)"
read continue
if [[ $continue = "y" ]]
then
echo "Starting base installation"

echo "Updating system==============================="
cd
sudo apt -y update
sudo apt -y upgrade
echo "System updated================================"


echo "Installing install_base dependencies=================="
sudo apt -y install supervisor python3 python3-venv python3-dev mysql-server supervisor nginx git
echo "Base dependencies installed==================="


echo "Installing SSL certificate===================="
sudo apt install -y software-properties-common
sudo add-apt-repository -y universe
sudo add-apt-repository -y ppa:certbot/certbot
sudo apt install -y certbot python-certbot-nginx
sudo certbot certonly --nginx -d $DOMAIN
echo "Installing SSL certificate complete==========="


echo "Configuring firewall=========================="
sudo apt -y install ufw
sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https
sudo ufw --force enable
echo "Configuring firewall complete================="



else
echo "Cancelling installation."
fi
cd